# Cloud Build configuration for vo-mfa-service
# Для ручного запуска: gcloud builds submit --config=cloudbuild.yaml --project=gen-lang-client-0960712901

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vo-mfa-service:latest', '.']
    timeout: '1800s'  # 30 минут на билд (модели большие)

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vo-mfa-service:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vo-mfa-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vo-mfa-service:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/vo-mfa-service:latest'

timeout: '2400s'  # 40 минут общий таймаут

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Быстрее билд
